# Generated by Django 3.1.4 on 2021-01-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Electronics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, null=True)),
                ('Description', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, null=True)),
                ('Department', models.CharField(choices=[('cit', 'cit'), ('sba', 'sba')], max_length=200, null=True)),
                ('Issue', models.CharField(max_length=200, null=True)),
                ('Code', models.IntegerField(null=True)),
                ('Status', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
