# Generated by Django 3.1.4 on 2021-01-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronics',
            name='Category',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='Department',
            field=models.CharField(choices=[('cit', 'Computing and Information Tecnology'), ('sba', 'Procurement and Logistics'), ('oasis', 'oasis'), ('lab A', 'lab A'), ('lab B', 'lab B')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='Issue',
            field=models.CharField(choices=[('Faulty Mouse', 'Faulty Keyboard'), ('Faulty System Unit', 'Faulty System Unit'), ('Faulty Monitor', 'Faulty Monitor'), ('Faulty Printer', 'Faulty Printer'), ('Faulty Projector', 'Faulty Projector')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='Status',
            field=models.CharField(choices=[('Recycled', 'Recycled'), ('Disposed', 'Disposed')], max_length=200, null=True),
        ),
    ]
