# Generated by Django 3.1.4 on 2021-01-02 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_auto_20210102_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignElectroncs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.CharField(choices=[('Recycled', 'Recycled'), ('Disposed', 'Disposed')], max_length=200, null=True)),
                ('Quantity', models.IntegerField(max_length=200, null=True)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.electronics')),
            ],
        ),
    ]
