# Generated by Django 3.1.4 on 2021-01-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_auto_20210104_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronics',
            name='Category',
            field=models.CharField(choices=[('Laptop', 'Laptop'), ('Desktop', 'Desktop'), ('Printer', 'Printer'), ('Projector', 'Projector'), ('Keyboard', 'Keyboard'), ('Mouse', 'Mouse')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='electronics',
            name='Description',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
