# Generated by Django 3.1.4 on 2021-01-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_auto_20210105_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electronics',
            old_name='Name',
            new_name='Brand',
        ),
        migrations.AddField(
            model_name='electronics',
            name='SerialNumber',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='electronics',
            name='YearOfRelease',
            field=models.DateField(null=True),
        ),
    ]
