# Generated by Django 3.1.4 on 2021-01-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_auto_20210105_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronics',
            name='YearOfRelease',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
